# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/42_miscellaneous.ipynb.

# %% auto 0
__all__ = ['additional_args', 'load_info']

# %% ../nbs/42_miscellaneous.ipynb 2
import joblib, argparse, os
from typing import Optional, List, Union

# %% ../nbs/42_miscellaneous.ipynb 3
from .core import *
from .data import *

# %% ../nbs/42_miscellaneous.ipynb 5
def additional_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('--expt_no', type=int, required=True)
    return parser.parse_known_args()[0]
    

# %% ../nbs/42_miscellaneous.ipynb 6
def load_info(save_file:str, meta_file:str, mname:str, sequence_length:Optional[int]=32):
    if os.path.exists(save_file):
        meta_info = joblib.load(save_file)
    else:
        meta_info = Info.from_txt(meta_file, max_sequence_length=sequence_length, padding=True, return_tensors='pt',
                                  info_column_names=["identifier", "input_text"], tokenization_column="input_text",
                                  use_tokenizer=True, tokenizer=mname)
        joblib.dump(meta_info, save_file)
    return meta_info
    
