# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/47_models.memtr.ipynb.

# %% auto 0
__all__ = ['MEMConfig', 'CrossCombinerBlock', 'Encoder', 'MEM001']

# %% ../../nbs/47_models.memtr.ipynb 2
import torch, torch.nn as nn, copy, re, torch.nn.functional as F

from typing import Optional, Tuple, List

from transformers import PretrainedConfig, DistilBertConfig, DistilBertPreTrainedModel, DistilBertModel
from transformers.models.distilbert.modeling_distilbert import TransformerBlock

from ..losses import *
from .PPP0XX import *

from .modeling_utils import *

# %% ../../nbs/47_models.memtr.ipynb 18
class MEMConfig(DBTConfig):

    def __init__(
        self,
        base_model_dim:Optional[int]=None,
        num_train_data:Optional[int]=None,
        num_test_data:Optional[int]=None,
        num_labels:Optional[int]=None,
        num_metadata:Optional[int]=None,
        data_aug_meta_prefix:Optional[str]=None,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.base_model_dim, self.num_train_data, self.num_test_data = base_model_dim, num_train_data, num_test_data
        self.num_labels, self.num_metadata, self.data_aug_meta_prefix = num_labels, num_metadata, data_aug_meta_prefix
        

# %% ../../nbs/47_models.memtr.ipynb 20
class CrossCombinerBlock(TransformerBlock):

    def __init__(self, config:PretrainedConfig):
        super().__init__(config)

    def post_init(self):
        for module in self.modules(): self._init_weights(module)

    def _initialize_weights(self, module: nn.Module):
        for m in module.modules(): self._init_weights(m)

    def _init_weights(self, module: nn.Module):
        if isinstance(module, nn.Linear):
            torch.nn.init.eye_(module.weight)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.LayerNorm):
            module.bias.data.zero_()
            module.weight.data.fill_(1.0)

    def forward(
        self,
        x: torch.Tensor,
        m: torch.Tensor,
        attn_mask: Optional[torch.Tensor] = None,
        head_mask: Optional[torch.Tensor] = None,
        output_attentions: bool = False,
    ) -> Tuple[torch.Tensor, ...]:
        
        # Cross-Attention
        ca_output = self.attention(
            query=x,
            key=m,
            value=m,
            mask=attn_mask,
            head_mask=head_mask,
            output_attentions=output_attentions,
        )
        if output_attentions:
            ca_output, ca_weights = ca_output  # (bs, seq_length, dim), (bs, n_heads, seq_length, seq_length)
        else:  # To handle these `output_attentions` or `output_hidden_states` cases returning tuples
            if type(ca_output) is not tuple:
                raise TypeError(f"ca_output must be a tuple but it is {type(ca_output)} type")
            ca_output = ca_output[0]
            
        ca_output = self.sa_layer_norm(ca_output + x)  # (bs, seq_length, dim)

        # Feed Forward Network
        ffn_output = self.ffn(ca_output)  # (bs, seq_length, dim)
        ffn_output: torch.Tensor = self.output_layer_norm(ffn_output + ca_output)  # (bs, seq_length, dim)

        output = (ffn_output,)
        if output_attentions:
            output = (ca_weights,) + output
        return output
        

# %% ../../nbs/47_models.memtr.ipynb 22
class Encoder(DistilBertPreTrainedModel):
    
    def __init__(
        self, 
        config
    ):
        super().__init__(config)
        self.config = config
        self.distilbert = DistilBertModel(config)
        
        self.register_buffer("trn_embeds", torch.randn(config.num_train_data, config.base_model_dim))
        self.register_buffer("tst_embeds", torch.randn(config.num_test_data, config.base_model_dim))
        self.register_buffer("lbl_embeds", torch.randn(config.num_labels, config.base_model_dim))
        
        self.projector = nn.Linear(config.dim, config.base_model_dim)
        
        config.dim = config.base_model_dim
        self.combiner = CrossCombinerBlock(config)
        
    @torch.no_grad()
    def init_dr_head(self):
        torch.nn.init.eye_(self.projector.weight)

    @torch.no_grad()
    def _init_train_embeddings(self, x:torch.Tensor):
        self.trn_embeds.copy_(x)

    @torch.no_grad()
    def _init_test_embeddings(self, x:torch.Tensor):
        self.tst_embeds.copy_(x)

    @torch.no_grad()
    def _init_label_embeddings(self, x:torch.Tensor):
        self.lbl_embeds.copy_(x)

    def _init_weights(self, module: nn.Module):
        super()._init_weights(module)
        if isinstance(module, Encoder):
            module.init_dr_head()

    def fuse_metadata(self, data_rep:torch.Tensor, meta_rep:torch.Tensor, data2ptr:torch.Tensor):
        num_metadata = data2ptr.max()
        assert (
            (data2ptr == num_metadata).all()
        ), "All the queries should have the same number of metadata."
        
        data_rep, meta_rep = data_rep.unsqueeze(1), meta_rep.view(data_rep.shape[0], num_metadata, -1)
        fused_data_rep = self.combiner(data_rep, meta_rep)[0]
        fused_data_rep = fused_data_rep.squeeze(1)
        return F.normalize(fused_data_rep, dim=1)

    def get_metadata_representation(
        self,
        data_input_ids:Optional[torch.Tensor]=None,
        data_attention_mask:Optional[torch.Tensor]=None,
        **kwargs,
    ):
        o = self.distilbert(
            input_ids=data_input_ids,
            attention_mask=data_attention_mask,
            **kwargs
        )
        meta_rep = Pooling.mean_pooling(o[0], data_attention_mask)
        return F.normalize(self.projector(meta_rep), dim=1)
            
    def forward(
        self, 
        data_idx:Optional[torch.Tensor] = None,
        data_aug_meta_prefix: Optional[str]=None,
        data_type:Optional[str]=None,
        **kwargs
    ):
        if data_type == "trn":
            data_rep = self.trn_embeds[data_idx]
        elif data_type == "tst":
            data_rep = self.tst_embeds[data_idx]
        elif data_type == "lbl":
            data_rep = self.lbl_embeds[data_idx]
        else:
            raise ValueError(f"Invalid input type: {data_type}")
        
        data_rep = F.normalize(data_rep, dim=1)

        fused_data_rep = meta_rep = None
        if data_aug_meta_prefix is not None:
            meta_kwargs = Parameters.from_meta_aug_prefix(data_aug_meta_prefix, **kwargs)            
            meta_rep = self.get_metadata_representation(meta_kwargs[data_aug_meta_prefix]["input_ids"],
                                                        meta_kwargs[data_aug_meta_prefix]["attention_mask"])
            fused_data_rep = self.fuse_metadata(data_rep, meta_rep, meta_kwargs[data_aug_meta_prefix]["data2ptr"])
        
        return data_rep, fused_data_rep, meta_rep
        

# %% ../../nbs/47_models.memtr.ipynb 25
class MEM001(DistilBertPreTrainedModel):
    use_generation,use_representation = False,True
    _tied_weights_keys = ["encoder.distilbert"]
    
    def __init__(
        self,
        config,
    ):
        super().__init__(config)
        self.config = config
        self.encoder = Encoder(config)
        
        loss_kwargs = {
            'margin': config.margin, 'n_negatives': config.num_negatives, 'tau': config.tau, 
            'apply_softmax': config.apply_softmax, 'reduce': config.reduction,
        }
        self.loss_fn = get_loss_function(config.loss_function)(**loss_kwargs)
        self.post_init()

    def _init_weights(self, module: nn.Module):
        super()._init_weights(module)
        if isinstance(module, BaseLoss):
            module.init_weights()
            
    def _tie_weights(self):
        self.distilbert = self.encoder.distilbert

    @torch.no_grad()
    def init_encoder_embeddings(self, trn_embeds:torch.Tensor, tst_embeds:torch.Tensor, lbl_embeds:torch.Tensor):
        self.encoder._init_train_embeddings(trn_embeds)
        self.encoder._init_test_embeddings(trn_embeds)
        self.encoder._init_label_embeddings(trn_embeds)

    def get_label_representation(self, data_idx:Optional[torch.Tensor]=None):
        return encoder(data_idx, data_type="lbl")

    def forward(
        self,
        data_idx:Optional[torch.Tensor]=None,
        
        lbl2data_data2ptr:Optional[torch.Tensor]=None,
        lbl2data_idx:Optional[torch.Tensor]=None,
        
        neg2data_data2ptr:Optional[torch.Tensor]=None,
        neg2data_idx:Optional[torch.Tensor]=None,

        plbl2data_data2ptr:Optional[torch.Tensor]=None,
        plbl2data_idx:Optional[torch.Tensor]=None,
        
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        return_dict: Optional[bool] = None,
        **kwargs
    ):
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        encoder = nn.DataParallel(module=self.encoder) if self.config.use_encoder_parallel else self.encoder

        data_meta_kwargs = Parameters.from_feat_meta_aug_prefix('data', config.data_aug_meta_prefix, **kwargs)
        data_repr, fused_data_repr, _ = encoder(data_idx=data_idx, data_aug_meta_prefix=config.data_aug_meta_prefix, 
                                                data_type="trn" if self.train else "tst", **data_meta_kwargs)
        
        loss = lbl2data_repr = neg2data_repr = None
        if lbl2data_idx is not None and neg2data_idx is not None:
            lbl2data_repr, _, _ = encoder(lbl2data_idx, data_type="lbl")
            neg2data_repr, _, _ = encoder(neg2data_idx, data_type="lbl")

            loss = self.loss_fn(fused_data_repr, pos_targ=lbl2data_repr, n_pos=lbl2data_data2ptr, pos_idx=lbl2data_idx, 
                                neg_targ=neg2data_repr, n_neg=neg2data_data2ptr, neg_idx=neg2data_idx, 
                                n_ppos=plbl2data_data2ptr, ppos_idx=plbl2data_idx, **kwargs)
            
        if not return_dict:
            o = (data_repr, lbl2data_repr)
            return ((loss,) + o) if loss is not None else o

        return XCModelOutput(
            loss=loss,
            data_fused_repr=fused_data_repr,
            data_repr=data_repr,
            lbl2data_repr=lbl2data_repr,
            neg2data_repr=neg2data_repr,
        )
        
